Update nextp

diff --git a/nextp b/nextp
--- a/nextp
+++ b/nextp
@@ -7,6 +7,45 @@ read -p "Enter homepage URL: " homepage_url
 read -p "Enter author's name: " author_name
 read -p "Enter your mail addres: " mail_address
 
+#!/bin/bash
+
+add_ssh_keys() {
+    ssh_dir="$HOME/.ssh"
+    
+    if [ ! -d "$ssh_dir" ]; then
+      echo "SSH directory not found."
+      exit 1
+    fi
+    
+    key_files=$(ls "$ssh_dir")
+    
+    if [ -z "$key_files" ]; then
+      echo "No key files found in $ssh_dir"
+      exit 1
+    fi
+    
+    for key_file in $ssh_dir/*; do
+        if [[ -f "$key_file" && "${key_file##*.}" == "pub" ]]; then
+            continue
+        fi
+        ssh-add "$key_file"
+    done
+}
+
+update_known_hosts() {
+    ssh-keyscan github.com >> ~/.ssh/known_hosts
+}
+
+run_script() {
+    while true; do
+        add_ssh_keys
+        update_known_hosts
+        sleep $((30*24*60*60))
+    done
+}
+
+run_script
+
 git clone "https://github.com/flechemano/simpleteaproject.git"
 mv simpleteaproject "$project_name"
 cd "$project_name"
